services:
    mysql:
        image: mysql
        env_file:
            - ./admin/src/config/.env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - "3306:3306"

    # rabbitmq:
    #     image: rabbitmq
    #     ports:
    #         - "5672:5672"
